# This file is used by Codemagic to configure the build process.
# For more information, see: https://docs.codemagic.io/yaml/yaml-getting-started/

workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean Flutter project
        script: |
          cd pharmacy_expiry_scanner
          flutter clean
          rm -rf build
          rm -rf ios/Pods
          rm -rf ios/.symlinks
      - name: Get Flutter packages
        script: |
          cd pharmacy_expiry_scanner
          flutter pub get
      - name: Analyze project source
        script: |
          cd pharmacy_expiry_scanner
          if [ -d test ]; then
            flutter analyze lib test
          else
            flutter analyze lib
          fi
      - name: Build iOS App
        script: |
          cd pharmacy_expiry_scanner
          flutter build ios --release --no-codesign
    artifacts:
      - pharmacy_expiry_scanner/build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
